name: flutterkaigi_2025_booth_game
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shake: ^3.0.0
  confetti: ^0.8.0
  auto_route: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
